/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.humble.ferry;

/**
 * Internal Only.
 * <p>
 * I meant that.
 * </p>
 * <p>
 * Really.  There's nothing here.
 * </p>
 */

public class Ferry {

  static {
    FerryJNI.noop();
  }
  /**
   * Don't allow creation of this object.
   */
  private Ferry(){}
  
  /** call this to force a load of all native components.
   * This is NOT normally required but can be useful in
   * some circumstances.
   */
  public static void load()
  {
    
  }
  /**
   * Internal Only.  Do not use.
   */
  public native static void init();
  
  /**
   * Internal Only.  Do not use.
   *
   */
  public final static int release(long cptr)
  {
    return FerryJNI.RefCounted_release(cptr, (RefCounted)null);
  }
  
  private static final int MAJOR_VERSION=0;

  /** The Major Version Number (Currently
   * &quot;{@value #MAJOR_VERSION}&quot;).
   * @return the major version number.
   */
  public static int getMajorVersion() { return MAJOR_VERSION; } 

  private static final int MINOR_VERSION=1;
  /** The Minor Version Number (Currently
   * &quot;{@value #MINOR_VERSION}&quot;).
   * @return the minor version number.
   */

  public static int getMinorVersion() { return MINOR_VERSION; } 

  private static final String VERSION=
  "0.1";

  /** The Version String (Currently {@value #VERSION}).
   * @return the version string
   */
  public static String getVersionString() { return VERSION; }  

}
