/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.humble.video;
import io.humble.ferry.*;
public class AudioSamples extends MediaRawData {
  // JNIHelper.swg: Start generated code
  // >>>>>>>>>>>>>>>>>>>>>>>>>>>
  /**
   * This method is only here to use some references and remove
   * a Eclipse compiler warning.
   */
  @SuppressWarnings("unused")
  private void noop()
  {
    IBuffer.make(null, 1);
  }
   
  private volatile long swigCPtr;

  /**
   * Internal Only.
   */
  protected AudioSamples(long cPtr, boolean cMemoryOwn) {
    super(VideoJNI.SWIGAudioSamplesUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }
  
  /**
   * Internal Only.
   */
  protected AudioSamples(long cPtr, boolean cMemoryOwn,
      java.util.concurrent.atomic.AtomicLong ref)
  {
    super(VideoJNI.SWIGAudioSamplesUpcast(cPtr),
     cMemoryOwn, ref);
    swigCPtr = cPtr;
  }
    
  /**
   * Internal Only.  Not part of public API.
   *
   * Get the raw value of the native object that obj is proxying for.
   *   
   * @param obj The java proxy object for a native object.
   * @return The raw pointer obj is proxying for.
   */
  protected static long getCPtr(AudioSamples obj) {
    if (obj == null) return 0;
    return obj.getMyCPtr();
  }

  /**
   * Internal Only.  Not part of public API.
   *
   * Get the raw value of the native object that we're proxying for.
   *   
   * @return The raw pointer we're proxying for.
   */  
  protected long getMyCPtr() {
    if (swigCPtr == 0) throw new IllegalStateException("underlying native object already deleted");
    return swigCPtr;
  }
  
  /**
   * Create a new AudioSamples object that is actually referring to the
   * exact same underlying native object.
   *
   * @return the new Java object.
   */
  @Override
  public AudioSamples copyReference() {
    if (swigCPtr == 0)
      return null;
    else
      return new AudioSamples(swigCPtr, swigCMemOwn, getJavaRefCount());
  }

  /**
   * Compares two values, returning true if the underlying objects in native code are the same object.
   *
   * That means you can have two different Java objects, but when you do a comparison, you'll find out
   * they are the EXACT same object.
   *
   * @return True if the underlying native object is the same.  False otherwise.
   */
  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof AudioSamples)
      equal = (((AudioSamples)obj).swigCPtr == this.swigCPtr);
    return equal;
  }
  
  /**
   * Get a hashable value for this object.
   *
   * @return the hashable value.
   */
  public int hashCode() {
     return (int)swigCPtr;
  }
  
  // <<<<<<<<<<<<<<<<<<<<<<<<<<<
  // JNIHelper.swg: End generated code
  

  public enum Format {
  /**
   * Different type of audio sample formats.
   * From libavutil/samplefmt.h
   * No sample format
   */
    SAMPLE_FMT_NONE(VideoJNI.AudioSamples_SAMPLE_FMT_NONE_get()),
  /**
   * unsigned 8 bits
   */
    SAMPLE_FMT_U8(VideoJNI.AudioSamples_SAMPLE_FMT_U8_get()),
  /**
   * signed 16 bits
   */
    SAMPLE_FMT_S16(VideoJNI.AudioSamples_SAMPLE_FMT_S16_get()),
  /**
   * signed 32 bits
   */
    SAMPLE_FMT_S32(VideoJNI.AudioSamples_SAMPLE_FMT_S32_get()),
  /**
   * float
   */
    SAMPLE_FMT_FLT(VideoJNI.AudioSamples_SAMPLE_FMT_FLT_get()),
  /**
   * double
   */
    SAMPLE_FMT_DBL(VideoJNI.AudioSamples_SAMPLE_FMT_DBL_get()),
  /**
   * unsigned 8 bits, planar
   */
    SAMPLE_FMT_U8P(VideoJNI.AudioSamples_SAMPLE_FMT_U8P_get()),
  /**
   * signed 16 bits, planar
   */
    SAMPLE_FMT_S16P(VideoJNI.AudioSamples_SAMPLE_FMT_S16P_get()),
  /**
   * signed 32 bits, planar
   */
    SAMPLE_FMT_S32P(VideoJNI.AudioSamples_SAMPLE_FMT_S32P_get()),
  /**
   * float, planar
   */
    SAMPLE_FMT_FLTP(VideoJNI.AudioSamples_SAMPLE_FMT_FLTP_get()),
  /**
   * double, planar
   */
    SAMPLE_FMT_DBLP(VideoJNI.AudioSamples_SAMPLE_FMT_DBLP_get());

    public final int swigValue() {
      return swigValue;
    }

    public static Format swigToEnum(int swigValue) {
      Format[] swigValues = Format.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (Format swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + Format.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private Format() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private Format(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private Format(Format swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

}
