/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.humble.video;


class VideoJNI {

// HumbleVideo.i: Start generated code
// >>>>>>>>>>>>>>>>>>>>>>>>>>>

  static {
    io.humble.ferry.Ferry.init();
    io.humble.video.Video.init();
    io.humble.video.Global.init();
  }
  public static void noop() {
    // Here only to force JNI library to load
  }
  
// <<<<<<<<<<<<<<<<<<<<<<<<<<<
// HumbleVideo.i: End generated code
  

  public final static native int IProperty_PROPERTY_CONST_get();
  public final static native int IProperty_PROPERTY_IMAGE_SIZE_get();
  public final static native int IProperty_PROPERTY_PIXEL_FMT_get();
  public final static native int IProperty_PROPERTY_SAMPLE_FMT_get();
  public final static native int IProperty_PROPERTY_UNKNOWN_get();
  public final static native int IProperty_FLAG_ENCODING_PARAM_get();
  public final static native int IProperty_FLAG_DECODING_PARAM_get();
  public final static native int IProperty_FLAG_METADATA_get();
  public final static native int IProperty_FLAG_AUDIO_PARAM_get();
  public final static native int IProperty_FLAG_VIDEO_PARAM_get();
  public final static native int IProperty_FLAG_SUBTITLE_PARAM_get();
  public final static native int IProperty_FLAG_FILTERING_PARAM_get();
  public final static native int IProperty_PROPERTY_SEARCH_DEFAULT_get();
  public final static native int IProperty_PROPERTY_SEARCH_CHILDREN_get();
  public final static native String IProperty_getName(long jarg1, IProperty jarg1_);
  public final static native String IProperty_getHelp(long jarg1, IProperty jarg1_);
  public final static native String IProperty_getUnit(long jarg1, IProperty jarg1_);
  public final static native int IProperty_getType(long jarg1, IProperty jarg1_);
  public final static native int IProperty_getFlags(long jarg1, IProperty jarg1_);
  public final static native long IProperty_getDefault(long jarg1, IProperty jarg1_);
  public final static native double IProperty_getDefaultAsDouble(long jarg1, IProperty jarg1_);
  public final static native int IProperty_getNumFlagSettings(long jarg1, IProperty jarg1_);
  public final static native long IProperty_getFlagConstant__SWIG_0(long jarg1, IProperty jarg1_, int jarg2);
  public final static native long IProperty_getFlagConstant__SWIG_1(long jarg1, IProperty jarg1_, String jarg2);
  public final static native long Global_NO_PTS_get();
  public final static native long Global_DEFAULT_PTS_PER_SECOND_get();
  public final static native long Global_getVersion();
  public final static native int Global_getVersionMajor();
  public final static native int Global_getVersionMinor();
  public final static native int Global_getVersionRevision();
  public final static native String Global_getVersionStr();
  public final static native int Global_getAVFormatVersion();
  public final static native String Global_getAVFormatVersionStr();
  public final static native int Global_getAVCodecVersion();
  public final static native String Global_getAVCodecVersionStr();
  public final static native void Global_init();
  public final static native void Global_setFFmpegLoggingLevel(int jarg1);
  public final static native int IPixelFormat_AV_PIX_FMT_NONE_get();
  public final static native int IPixelFormat_AV_PIX_FMT_RGBA64BE_get();
  public final static native int IPixelFormat_AV_PIX_FMT_0RGB_get();
  public final static native int IPixelFormat_YUV_Y_get();
  public final static native int IPixelFormat_YUV_U_get();
  public final static native int IPixelFormat_YUV_V_get();
  public final static native int IRational_ROUND_ZERO_get();
  public final static native int IRational_ROUND_INF_get();
  public final static native int IRational_ROUND_DOWN_get();
  public final static native int IRational_ROUND_UP_get();
  public final static native int IRational_ROUND_NEAR_INF_get();
  public final static native int IRational_ROUND_PASS_MINMAX_get();
  public final static native int IRational_getNumerator(long jarg1, IRational jarg1_);
  public final static native int IRational_getDenominator(long jarg1, IRational jarg1_);
  public final static native long IRational_copy(long jarg1, IRational jarg1_);
  public final static native int IRational_compareTo(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native int IRational_sCompareTo(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native double IRational_getDouble(long jarg1, IRational jarg1_);
  public final static native int IRational_reduce(long jarg1, IRational jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native int IRational_sReduce(long jarg1, IRational jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long IRational_multiply(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_sMultiply(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_divide(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_sDivide(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_subtract(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_sSubtract(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_add(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_sAdd(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_rescale__SWIG_0(long jarg1, IRational jarg1_, long jarg2, long jarg3, IRational jarg3_);
  public final static native long IRational_sRescale__SWIG_0(long jarg1, long jarg2, IRational jarg2_, long jarg3, IRational jarg3_);
  public final static native long IRational_make__SWIG_0();
  public final static native long IRational_make__SWIG_1(double jarg1);
  public final static native long IRational_make__SWIG_2(long jarg1, IRational jarg1_);
  public final static native long IRational_make__SWIG_3(int jarg1, int jarg2);
  public final static native long IRational_rescale__SWIG_1(long jarg1, IRational jarg1_, long jarg2, long jarg3, IRational jarg3_, int jarg4);
  public final static native long IRational_sRescale__SWIG_1(long jarg1, long jarg2, IRational jarg2_, long jarg3, IRational jarg3_, int jarg4);
  public final static native long IRational_rescale__SWIG_2(long jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6);
  public final static native void IRational_setNumerator(long jarg1, IRational jarg1_, int jarg2);
  public final static native void IRational_setDenominator(long jarg1, IRational jarg1_, int jarg2);
  public final static native void IRational_setValue(long jarg1, IRational jarg1_, double jarg2);
  public final static native double IRational_getValue(long jarg1, IRational jarg1_);
  public final static native boolean IRational_isFinalized(long jarg1, IRational jarg1_);
  public final static native void IRational_init(long jarg1, IRational jarg1_);
  public final static native long SWIGIPropertyUpcast(long jarg1);
  public final static native long SWIGGlobalUpcast(long jarg1);
  public final static native long SWIGIPixelFormatUpcast(long jarg1);
  public final static native long SWIGIRationalUpcast(long jarg1);
}
