/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.humble.video;


class VideoJNI {

// HumbleVideo.i: Start generated code
// >>>>>>>>>>>>>>>>>>>>>>>>>>>

  static {
    io.humble.ferry.Ferry.init();
    io.humble.video.Video.init();
    io.humble.video.Global.init();
  }
  public static void noop() {
    // Here only to force JNI library to load
  }
  
// <<<<<<<<<<<<<<<<<<<<<<<<<<<
// HumbleVideo.i: End generated code
  

  public final static native long Global_NO_PTS_get();
  public final static native long Global_DEFAULT_PTS_PER_SECOND_get();
  public final static native long Global_getVersion();
  public final static native int Global_getVersionMajor();
  public final static native int Global_getVersionMinor();
  public final static native int Global_getVersionRevision();
  public final static native String Global_getVersionStr();
  public final static native int Global_getAVFormatVersion();
  public final static native String Global_getAVFormatVersionStr();
  public final static native int Global_getAVCodecVersion();
  public final static native String Global_getAVCodecVersionStr();
  public final static native void Global_init();
  public final static native void Global_setFFmpegLoggingLevel(int jarg1);
  public final static native int Codec_ID_BRENDER_PIX_get();
  public final static native int Codec_ID_Y41P_get();
  public final static native int Codec_ID_ESCAPE130_get();
  public final static native int Codec_ID_EXR_get();
  public final static native int Codec_ID_AVRP_get();
  public final static native int Codec_ID_012V_get();
  public final static native int Codec_ID_G2M_get();
  public final static native int Codec_ID_AVUI_get();
  public final static native int Codec_ID_AYUV_get();
  public final static native int Codec_ID_TARGA_Y216_get();
  public final static native int Codec_ID_V308_get();
  public final static native int Codec_ID_V408_get();
  public final static native int Codec_ID_YUV4_get();
  public final static native int Codec_ID_SANM_get();
  public final static native int Codec_ID_PAF_VIDEO_get();
  public final static native int Codec_ID_AVRN_get();
  public final static native int Codec_ID_CPIA_get();
  public final static native int Codec_ID_XFACE_get();
  public final static native int Codec_ID_SGIRLE_get();
  public final static native int Codec_ID_MVC1_get();
  public final static native int Codec_ID_MVC2_get();
  public final static native int Codec_ID_FIRST_AUDIO_get();
  public final static native int Codec_ID_PCM_S16LE_get();
  public final static native int Codec_ID_PCM_S24LE_PLANAR_get();
  public final static native int Codec_ID_PCM_S32LE_PLANAR_get();
  public final static native int Codec_ID_PCM_S16BE_PLANAR_get();
  public final static native int Codec_ID_ADPCM_IMA_QT_get();
  public final static native int Codec_ID_VIMA_get();
  public final static native int Codec_ID_ADPCM_AFC_get();
  public final static native int Codec_ID_ADPCM_IMA_OKI_get();
  public final static native int Codec_ID_AMR_NB_get();
  public final static native int Codec_ID_RA_144_get();
  public final static native int Codec_ID_ROQ_DPCM_get();
  public final static native int Codec_ID_MP2_get();
  public final static native int Codec_ID_FFWAVESYNTH_get();
  public final static native int Codec_ID_8SVX_RAW_get();
  public final static native int Codec_ID_SONIC_get();
  public final static native int Codec_ID_SONIC_LS_get();
  public final static native int Codec_ID_PAF_AUDIO_get();
  public final static native int Codec_ID_OPUS_get();
  public final static native int Codec_ID_TAK_get();
  public final static native int Codec_ID_EVRC_get();
  public final static native int Codec_ID_SMV_get();
  public final static native int Codec_ID_FIRST_SUBTITLE_get();
  public final static native int Codec_ID_DVD_SUBTITLE_get();
  public final static native int Codec_ID_MICRODVD_get();
  public final static native int Codec_ID_EIA_608_get();
  public final static native int Codec_ID_JACOSUB_get();
  public final static native int Codec_ID_SAMI_get();
  public final static native int Codec_ID_REALTEXT_get();
  public final static native int Codec_ID_SUBVIEWER1_get();
  public final static native int Codec_ID_SUBVIEWER_get();
  public final static native int Codec_ID_SUBRIP_get();
  public final static native int Codec_ID_WEBVTT_get();
  public final static native int Codec_ID_MPL2_get();
  public final static native int Codec_ID_VPLAYER_get();
  public final static native int Codec_ID_PJS_get();
  public final static native int Codec_ID_FIRST_UNKNOWN_get();
  public final static native int Codec_ID_TTF_get();
  public final static native int Codec_ID_BINTEXT_get();
  public final static native int Codec_ID_XBIN_get();
  public final static native int Codec_ID_IDF_get();
  public final static native int Codec_ID_OTF_get();
  public final static native int Codec_ID_SMPTE_KLV_get();
  public final static native int Codec_ID_PROBE_get();
  public final static native int Codec_ID_MPEG2TS_get();
  public final static native int Codec_ID_MPEG4SYSTEMS_get();
  public final static native int Codec_ID_FFMETADATA_get();
  public final static native int IProperty_PROPERTY_CONST_get();
  public final static native int IProperty_PROPERTY_IMAGE_SIZE_get();
  public final static native int IProperty_PROPERTY_PIXEL_FMT_get();
  public final static native int IProperty_PROPERTY_SAMPLE_FMT_get();
  public final static native int IProperty_PROPERTY_UNKNOWN_get();
  public final static native int IProperty_FLAG_ENCODING_PARAM_get();
  public final static native int IProperty_FLAG_DECODING_PARAM_get();
  public final static native int IProperty_FLAG_METADATA_get();
  public final static native int IProperty_FLAG_AUDIO_PARAM_get();
  public final static native int IProperty_FLAG_VIDEO_PARAM_get();
  public final static native int IProperty_FLAG_SUBTITLE_PARAM_get();
  public final static native int IProperty_FLAG_FILTERING_PARAM_get();
  public final static native int IProperty_PROPERTY_SEARCH_DEFAULT_get();
  public final static native int IProperty_PROPERTY_SEARCH_CHILDREN_get();
  public final static native String IProperty_getName(long jarg1, IProperty jarg1_);
  public final static native String IProperty_getHelp(long jarg1, IProperty jarg1_);
  public final static native String IProperty_getUnit(long jarg1, IProperty jarg1_);
  public final static native int IProperty_getType(long jarg1, IProperty jarg1_);
  public final static native int IProperty_getFlags(long jarg1, IProperty jarg1_);
  public final static native long IProperty_getDefault(long jarg1, IProperty jarg1_);
  public final static native double IProperty_getDefaultAsDouble(long jarg1, IProperty jarg1_);
  public final static native int IProperty_getNumFlagSettings(long jarg1, IProperty jarg1_);
  public final static native long IProperty_getFlagConstant__SWIG_0(long jarg1, IProperty jarg1_, int jarg2);
  public final static native long IProperty_getFlagConstant__SWIG_1(long jarg1, IProperty jarg1_, String jarg2);
  public final static native int IPixelFormat_AV_PIX_FMT_NONE_get();
  public final static native int IPixelFormat_AV_PIX_FMT_RGBA64BE_get();
  public final static native int IPixelFormat_AV_PIX_FMT_0RGB_get();
  public final static native int IPixelFormat_YUV_Y_get();
  public final static native int IPixelFormat_YUV_U_get();
  public final static native int IPixelFormat_YUV_V_get();
  public final static native int IRational_ROUND_ZERO_get();
  public final static native int IRational_ROUND_INF_get();
  public final static native int IRational_ROUND_DOWN_get();
  public final static native int IRational_ROUND_UP_get();
  public final static native int IRational_ROUND_NEAR_INF_get();
  public final static native int IRational_ROUND_PASS_MINMAX_get();
  public final static native int IRational_getNumerator(long jarg1, IRational jarg1_);
  public final static native int IRational_getDenominator(long jarg1, IRational jarg1_);
  public final static native long IRational_copy(long jarg1, IRational jarg1_);
  public final static native int IRational_compareTo(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native int IRational_sCompareTo(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native double IRational_getDouble(long jarg1, IRational jarg1_);
  public final static native int IRational_reduce(long jarg1, IRational jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native int IRational_sReduce(long jarg1, IRational jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long IRational_multiply(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_sMultiply(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_divide(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_sDivide(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_subtract(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_sSubtract(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_add(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_sAdd(long jarg1, IRational jarg1_, long jarg2, IRational jarg2_);
  public final static native long IRational_rescale__SWIG_0(long jarg1, IRational jarg1_, long jarg2, long jarg3, IRational jarg3_);
  public final static native long IRational_sRescale__SWIG_0(long jarg1, long jarg2, IRational jarg2_, long jarg3, IRational jarg3_);
  public final static native long IRational_make__SWIG_0();
  public final static native long IRational_make__SWIG_1(double jarg1);
  public final static native long IRational_make__SWIG_2(long jarg1, IRational jarg1_);
  public final static native long IRational_make__SWIG_3(int jarg1, int jarg2);
  public final static native long IRational_rescale__SWIG_1(long jarg1, IRational jarg1_, long jarg2, long jarg3, IRational jarg3_, int jarg4);
  public final static native long IRational_sRescale__SWIG_1(long jarg1, long jarg2, IRational jarg2_, long jarg3, IRational jarg3_, int jarg4);
  public final static native long IRational_rescale__SWIG_2(long jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6);
  public final static native void IRational_setNumerator(long jarg1, IRational jarg1_, int jarg2);
  public final static native void IRational_setDenominator(long jarg1, IRational jarg1_, int jarg2);
  public final static native void IRational_setValue(long jarg1, IRational jarg1_, double jarg2);
  public final static native double IRational_getValue(long jarg1, IRational jarg1_);
  public final static native boolean IRational_isFinalized(long jarg1, IRational jarg1_);
  public final static native void IRational_init(long jarg1, IRational jarg1_);
  public final static native int ContainerFormat_MEDIA_UNKNOWN_get();
  public final static native int ContainerFormat_MEDIA_VIDEO_get();
  public final static native int ContainerFormat_MEDIA_AUDIO_get();
  public final static native int ContainerFormat_MEDIA_DATA_get();
  public final static native int ContainerFormat_MEDIA_SUBTITLE_get();
  public final static native int ContainerFormat_MEDIA_ATTACHMENT_get();
  public final static native int ContainerFormat_INVALID_FLAG_get();
  public final static native int ContainerFormat_NO_FILE_get();
  public final static native int ContainerFormat_NEED_NUMBER_get();
  public final static native int ContainerFormat_SHOW_IDS_get();
  public final static native int ContainerFormat_RAW_PICTURE_get();
  public final static native int ContainerFormat_GLOBAL_HEADER_get();
  public final static native int ContainerFormat_NO_TIMESTAMPS_get();
  public final static native int ContainerFormat_GENERIC_INDEX_get();
  public final static native int ContainerFormat_TIMESTAMP_DISCONTINUITIES_get();
  public final static native int ContainerFormat_VARIABLE_FPS_get();
  public final static native int ContainerFormat_NO_DIMENSIONS_get();
  public final static native int ContainerFormat_NO_STREAMS_get();
  public final static native int ContainerFormat_NO_BINARY_SEARCH_get();
  public final static native int ContainerFormat_NO_GENERIC_SEARCH_get();
  public final static native int ContainerFormat_NO_BYTE_SEEKING_get();
  public final static native int ContainerFormat_ALLOW_FLUSH_get();
  public final static native int ContainerFormat_NONSTRICT_TIMESTAMPS_get();
  public final static native int ContainerFormat_SEEK_TO_PTS_get();
  public final static native String ContainerFormat_getName(long jarg1, ContainerFormat jarg1_);
  public final static native String ContainerFormat_getLongName(long jarg1, ContainerFormat jarg1_);
  public final static native String ContainerFormat_getExtensions(long jarg1, ContainerFormat jarg1_);
  public final static native int ContainerFormat_getFlags(long jarg1, ContainerFormat jarg1_);
  public final static native int ContainerFormat_getNumSupportedCodecs(long jarg1, ContainerFormat jarg1_);
  public final static native int ContainerFormat_getSupportedCodecId(long jarg1, ContainerFormat jarg1_, int jarg2);
  public final static native long ContainerFormat_getSupportedCodecTag(long jarg1, ContainerFormat jarg1_, int jarg2);
  public final static native void delete_ContainerFormat(long jarg1);
  public final static native String OutputFormat_getName(long jarg1, OutputFormat jarg1_);
  public final static native String OutputFormat_getLongName(long jarg1, OutputFormat jarg1_);
  public final static native String OutputFormat_getExtensions(long jarg1, OutputFormat jarg1_);
  public final static native int OutputFormat_getFlags(long jarg1, OutputFormat jarg1_);
  public final static native int OutputFormat_getDefaultAudioCodecId(long jarg1, OutputFormat jarg1_);
  public final static native int OutputFormat_getDefaultVideoCodecId(long jarg1, OutputFormat jarg1_);
  public final static native int OutputFormat_getDefaultSubtitleCodecId(long jarg1, OutputFormat jarg1_);
  public final static native String OutputFormat_getMimeType(long jarg1, OutputFormat jarg1_);
  public final static native long OutputFormat_guessFormat(String jarg1, String jarg2, String jarg3);
  public final static native int OutputFormat_guessCodec(long jarg1, OutputFormat jarg1_, String jarg2, String jarg3, String jarg4, int jarg5);
  public final static native long SWIGGlobalUpcast(long jarg1);
  public final static native long SWIGCodecUpcast(long jarg1);
  public final static native long SWIGIPropertyUpcast(long jarg1);
  public final static native long SWIGIPixelFormatUpcast(long jarg1);
  public final static native long SWIGIRationalUpcast(long jarg1);
  public final static native long SWIGContainerFormatUpcast(long jarg1);
  public final static native long SWIGOutputFormatUpcast(long jarg1);
}
