#! /usr/bin/env python
#
# Setup the Python environment, create an asciidoc manpage, and then create the final manpage
#

import sys
import os
from os.path import realpath, dirname
if sys.version_info < (3,0):
    sys.path.insert(0, dirname(dirname(dirname(realpath(__file__))))+os.sep+'python')
else:
    sys.path.insert(0, dirname(dirname(dirname(realpath(__file__))))+os.sep+'python'+os.sep+'python3')
sys.path.append(".")

import cxxtest

cxxtest.create_manpage()

