/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.humble.video;
import io.humble.ferry.*;
public class SWIGTYPE_p_MediaEncoded {
  private long swigCPtr;

  protected SWIGTYPE_p_MediaEncoded(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_MediaEncoded() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_MediaEncoded obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

